# Generated by Django 5.2.17 on 2026-09-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_material_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
