# Generated by Django 5.2.17 on 2026-09-23 06:10

from django.db import migrations, models


DEFAULTS = [
    "per sq ft",
    "per sq m",
    "per running ft",
    "per running m",
    "per piece",
    "per set",
    "per kg",
    "per litre",
    "per bag",
    "per sheet",
    "per roll",
    "lump sum",
]


def seed(apps, schema_editor):
    """Arrive with a usable list rather than an empty dropdown.

    Rate units, not pack sizes: what belongs on the client's line is what the
    price is per. The order is the order they are offered in, roughly by how
    often a project needs them.
    """
    Unit = apps.get_model("portal", "Unit")
    Unit.objects.bulk_create(
        [Unit(label=label, order=index) for index, label in enumerate(DEFAULTS)]
    )


def unseed(apps, schema_editor):
    apps.get_model("portal", "Unit").objects.filter(label__in=DEFAULTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_material_photo_materialphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers come first in the list.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop offering this without losing it.')),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
        migrations.RunPython(seed, unseed),
    ]
