# Generated by Django 5.2.17 on 2026-09-23 06:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


DEFAULTS = [
    ("No tax", "0.00"),
    ("GST 5%", "5.00"),
    ("GST 12%", "12.00"),
    ("GST 18%", "18.00"),
    ("GST 28%", "28.00"),
]


def seed(apps, schema_editor):
    """The GST slabs, so the dropdown is usable on day one.

    "No tax" first and explicit: an unregistered practice raises every invoice
    at nil, and leaving them to work out that blank means nil is how a rate
    ends up typed in by hand.
    """
    TaxRate = apps.get_model("portal", "TaxRate")
    TaxRate.objects.bulk_create(
        [
            TaxRate(label=label, percent=percent, order=index)
            for index, (label, percent) in enumerate(DEFAULTS)
        ]
    )


def unseed(apps, schema_editor):
    apps.get_model("portal", "TaxRate").objects.filter(
        label__in=[label for label, _ in DEFAULTS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Shown in the dropdown, e.g. GST 18%.', max_length=40)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to stop offering this without losing it.')),
            ],
            options={
                'ordering': ('order', 'percent'),
            },
        ),
        migrations.AddField(
            model_name='architect',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='default_tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='architect',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, verbose_name='GSTIN'),
        ),
        migrations.AddField(
            model_name='architect',
            name='invoice_terms',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('estimate', 'Estimate'), ('invoice', 'Invoice')], default='invoice', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('access_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('number', models.CharField(max_length=30)),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('from_name', models.CharField(max_length=120)),
                ('from_address', models.TextField(blank=True)),
                ('from_gstin', models.CharField(blank=True, max_length=20)),
                ('from_phone', models.CharField(blank=True, max_length=20)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_bank', models.TextField(blank=True)),
                ('to_name', models.CharField(max_length=120)),
                ('to_address', models.TextField(blank=True)),
                ('to_phone', models.CharField(blank=True, max_length=20)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('to_gstin', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='portal.project')),
            ],
            options={
                'ordering': ('-issued_on', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portal.invoice')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.material')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portal.milestone')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('project', 'kind', 'number'), name='unique_number_per_series'),
        ),
        migrations.RunPython(seed, unseed),
    ]
