# Generated by Django 5.2.17 on 2026-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_taxrate_architect_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16),
        ),
    ]
